### ISSUE TITLE
All write-related filesystem errors are being reported as "permission denied"

### ISSUE THREAD

**Issue by keichan34** [unvt/charites#130]
**Describe the bug**
All write-related filesystem errors are being reported as "permission denied"

https://github.com/unvt/charites/blob/88c921556e856f0eea17de98430e091e4a13fdd4/src/lib/yaml-writer.ts#L33-L37

**To Reproduce**
Run convert with a destination of a volume that is full or read-only

**Expected behavior**
A detailed error describing that the volume is full

**Charites Version:**

- Charites version: 0.X.X

**Desktop (please complete the following information):**

- OS: [e.g. Windows]

**Additional context**
I think that the underlying error should be exposed instead of overwriting it. This has lead to confusing error reports: #56 , where the error reports "permission denied" when it should `ENOENT: no such file or directory` (that bug was because the parent directory wasn't being created, which throws the no such file or directory error)

**Comment by ubukawa** [comment]
Dear @keichan34  and @miya0001 ,

Thank you very much for improving charites!
If it is possible, can you also update npm package so that we can use the charites with improvement by the pull request #129?
 https://github.com/unvt/charites/pull/129
 
 I can use it by cloning the repository, but it would be easy for users to install via npm.
 Thank you very much for your kind attention!
 
 Best regards, Taro Ubukawa

**Comment by keichan34** [comment]
@ubukawa Sorry for the late release! I just merged a couple outstanding pull requests and created a new release [0.3.0](https://github.com/unvt/charites/releases/tag/v0.3.0) :)

**Comment by ubukawa** [comment]
Dear @keichan34 ,
Thank you very very much for your prompt response!
I really appreciate your continued contribution.
