### ISSUE TITLE
Style load forced to HTTP

### ISSUE THREAD

**Issue by pnorman** [unvt/charites#156]
**Describe the bug**
When hosting charites on https, the `shared.js` code forces connections to downgrade to HTTP, causing mixed content errors

**To Reproduce**

1. Set up a HTTPS terminator, pointing at charites
1. Load the page.
1. Mixed content errors occur

Specifically, the errors are in `shared.js`

```js
      socket.addEventListener('message', (message) => {
        const data = JSON.parse(message.data)
        if (data.event === 'styleUpdate') {
          map.setStyle(`http://${window.location.host}/style.json`)
        } else if (data.event === 'spriteUpdate') {
          map.setStyle(`http://${window.location.host}/style.json`, {
            diff: false,
          })
        }
      })
```

The setStyle calls force the connection to change from HTTP to HTTPS

**Expected behavior**
The same protocol is used

**Charites Version:**

- Charites version: 0.4.0

**Desktop (please complete the following information):**

N/A, desktop not used

**Comment by ubukawa** [comment]
Hello, @pnorman , thank you for sharing.

I have never tried a HTTPS terminator as you did, but I just used "charites serve" command and host the live preview in my localhost. (or from local server through http protocol.)

As far as I know, the charites is designed for http only now because the serve.ts use http, and there is no information on the certificate.
https://github.com/unvt/charites/blob/main/src/commands/serve.ts#L65-L68

I am not good at coding, but I think we can create another command like "charites serve-https" in the future by adding another version of "serve.ts" and related scripts.

(On the other hand, charites is a styling tool and I am not using it for a permanent hosting. 
So, at least to me, http is good enough.)


I would appreciate any advice from @keichan34 and/or @miya0001 if you have any.

Please excuse me if I am wrong in terms of coding!
Thank you!!

**Comment by pnorman** [comment]
No, there shouldn't be another command. shared.js should be agnostic to protocol - is there any reason a relative URL wouldn't work? I'll have to test when I get some time.
