### ISSUE TITLE
Recommended environment for charites

### ISSUE THREAD

**Issue by ubukawa** [unvt/charites#39]
Warm greetings!
Do you have any recommendation on the charites environment?

It seems that charites work well on OSX and Ubuntu.
In windows environment, I am using charities on Docker (unvt/nanban).

It would be helpful if you can explain these recommended environment at the "install" section of the readme.
What do you think?

Thank you for your attention!

**Comment by JinIgarashi** [comment]
@ubukawa It is great idea to specify recommended environment for the module. I think this charites might not work well in some environment such as arm64 (eg., M1 Mac) because some of NPM packages like sprite-zero uses mapnik. I also think Docker can be the best environment in Windows, or WSL might work well for charites. Furthermore, version of Nodejs also can be worth mentioning in README (v14 or above?).
Could you make pull request to add such information on README? Thanks.

**Comment by ubukawa** [comment]
Thank you @JinIgarashi .
I made a pull request. Please feel free to add any other description to them.

Thank you. and I will close this issue.
