### ISSUE TITLE
Can charites serve work properly on Linux?

### ISSUE THREAD

**Issue by ubukawa** [unvt/charites#88]
Warm greeting! Thank you once again for the charites development!

After my work in my own PC, now I would like to share the styling work with my colleagues and use charites in Linux.
I have found some issue here. I would appreciate if if you could kindly confirm it!

**Describe the bug**
During charites serve, updated file is not detected automatically.

**To Reproduce**

* Install charites on Red Hat Enterprise Linux (release 8.4)
* run "charites serve"
* Open the Charites Live Preview through http://(ip address):8080
* update yaml files under layers
* Then, edit is not detected automatically. 
     * CLI does not show any message.
     * Charites Live Preview does not change.
     * (IF I type F5 on the browser, the edit is then reflected on Charites Live Preview, but no message in CLI..)

**Expected behavior**
Even in Linux, I expected that the update/edit of yml file is automatically detected and live-view automatically update.

**Screenshots**
![2022-01-24-charites](https://user-images.githubusercontent.com/59204379/150907999-26f4a326-f7dc-44ef-bb0b-f38ef98e73be.png)

**Charites Version:**
- Charites version: 0.X.X

**Desktop (please complete the following information):**

- Server OS: Red Hat Enterprise Linux (release 8.4)
- Browser: Google Chrome in Windows PC
(Charites is run on Linux server while I saw the preview from other PC.)

**Additional context**

**Comment by keichan34** [comment]
When I tried this (server: Ubuntu Linux, browser: Chrome on macOS on another PC), I got an error in the console:

```
WebSocket connection to: `ws://localhost:8080` failed
```

Because the WebSocket connection is used to tell the browser about new updates to styles, I think that this may be the culprit. A fix to dynamically change the hostname of the WebSocket connection may help?

https://github.com/unvt/charites/blob/main/provider/default/app.js#L7
https://github.com/unvt/charites/blob/main/provider/geolonia/app.js#L7
https://github.com/unvt/charites/blob/main/provider/mapbox/app.js#L9
